#!/usr/bin/env python
import os
import pickle
from mva.cmd import get_parser

args = get_parser(actions=False).parse_args()

from mva.categories import *
from mva.analysis import get_analysis
from mva.plotting import draw_channel_array
from mva.variables import VARIABLES
from mva import CACHE_DIR
from rootpy.tree import Cut
from rootpy.plotting import Hist
from math import pi

analysis = get_analysis(
    args, year=2012,
    systematics=False)

analysis.normalize(Category_Preselection_PiPi)
with open(os.path.join(CACHE_DIR, 'binning/binning_vbf_125_12.pickle')) as f:
    binning = pickle.load(f)
#templates = {'BDTScore_vbf_1': Hist(binning, type='D')}
templates = {'Acoplanarity_rho_cluster': Hist(3,0.0,math.pi, type='D')}

draw_channel_array(
    analysis, {'Acoplanarity_rho_cluster': VARIABLES['Acoplanarity_rho_cluster']},
    templates=templates,
    mass=125, mode='combined', signal_scale=1.42,
    signal_on_top=False,
    signal_colors=['blue'],
    signal_odd_colors=['red'],
    category=Category_VBF_PiPi_SR,
    region=analysis.target_region,
    show_ratio=False,
    output_dir='plots/categories',
    output_suffix='_2012',
    output_formats=['pdf', 'eps'],
    arrow_values=[100],
    log_ypadding=(0.3, 0),
    logy_min=0.11,
    uniform=True)
