#!/usr/bin/env python

import sys
from mva import cmd, MMC_MASS
from mva.samples import Higgs
from mva.workspace import (
    write_workspaces, cp_workspace)
from mva.analysis import get_analysis
from mva.massregions import MassRegions
from mva.variables import VARIABLES
from rootpy.plotting import Hist

parser = cmd.analysis_parser(cmd.general_parser(
    multi_years=True, multi_categories=True))
args = parser.parse_args()

params = {}
years = [2012]
categories = ['cp']
masses = [125]
if len(categories) == 1 and len(years) > 1:
    categories = categories * len(years)
elif len(categories) != len(years):
    sys.exit("specify the same number of category definitions as years")

signal_regions = {}
control_regions = {}

for year, year_categories in zip(years, categories):

    # 8TeV had-had mu value = 1.42
    analysis = get_analysis(args, year=year, mu=1.42)
    sr, cr = cp_workspace(analysis=analysis,
                          categories=year_categories,
                          masses=masses,
                          systematics=args.systematics,
                          **params)
    signal_regions[year] = sr
    control_regions[year] = cr
print signal_regions
print control_regions
suffix = analysis.get_suffix(year=False)
path = 'workspaces/hh_cp{0}'.format(suffix.lower())
write_workspaces(path, 'hh_cp', signal_regions, controls=control_regions)

